apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
   - 'manifests/upstream'

patches:
- path: manifests/all-namespaces/patches/prometheus-ClusterRole.yaml
- path: manifests/prometheus-pvc/patches/prometheus-prometheus.yaml
