apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  retention: 90d
  storage:
    volumeClaimTemplate:
      apiVersion: 'v1'
      kind: Persistentvolumeclaim
      spec:
        # storageClassName: default
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
